### PR TITLE
ver bump

### PR DESCRIPTION
**Pull request by tenox7**

### CODE REVIEW

**Comment by edgar-bonet** [comment]
I think the CI is failing because the PR is missing this change:

```diff
diff --git a/recordings/expected.txt b/recordings/expected.txt
index 0787a65..f191fdc 100644
--- a/recordings/expected.txt
+++ b/recordings/expected.txt
@@ -19,7 +19,7 @@
 |  │                                                                                       |
 |  └─────────────────────────────────────────────────────────────────────────────────────> |
 |     X                                                           Thu Jan  1 00:00:00 1970 |
-|     [0m[7m [0m                                            https://github.com/tenox7/ttyplot 1.6.2 |
+|     [0m[7m [0m                                            https://github.com/tenox7/ttyplot 1.6.5 |
 +------------------------------------------------------------------------------------------+
 
 [90x20] Frame 2:
@@ -43,7 +43,7 @@
 |  │                                                                                    [0m[7mX[0m[0m[7mX[0m |
 |  └─────────────────────────────────────────────────────────────────────────────────────> |
 |     X last=3.0 min=1.0 max=3.0 avg=2.0                          Thu Jan  1 00:00:00 1970 |
-|     [0m[7m [0m last=4.0 min=2.0 max=4.0 avg=3.0           https://github.com/tenox7/ttyplot 1.6.2 |
+|     [0m[7m [0m last=4.0 min=2.0 max=4.0 avg=3.0           https://github.com/tenox7/ttyplot 1.6.5 |
 +------------------------------------------------------------------------------------------+
 
 [90x20] Frame 3:
@@ -67,6 +67,6 @@
 |  │                                                                                    [0m[7mX[0m[0m[7mX[0m |
 |  └─────────────────────────────────────────────────────────────────────────────────────> |
 |     X last=3.0 min=1.0 max=3.0 avg=2.0                          Thu Jan  1 00:00:00 1970 |
-|     [0m[7m [0m last=4.0 min=2.0 max=4.0 avg=3.0           https://github.com/tenox7/ttyplot 1.6.2 |
+|     [0m[7m [0m last=4.0 min=2.0 max=4.0 avg=3.0           https://github.com/tenox7/ttyplot 1.6.5 |
 +------------------------------------------------------------------------------------------+
 
```

**Comment by chenrui333** [comment]
@tenox7 any luck with this pr?

**Comment by tenox7** [comment]
@edgar-bonet or @hartwork please approve and merge? thanks

**Review by edgar-bonet — APPROVED** [review]
Oh, this looks a bit messy to me. How could we merge this pull request? Ideally, when a PR is just one main commit + one fixup, I would do a squash merge. This, however, would leave the version-tagged commit out of the master's history (kind of weird), and most likely out of GitHub's “Releases” page (clearly undesirable). Creating a merge commit would leave the tagged commit on a side branch, out of the “mainline“ history of `git log --first-parent`. I guess the best option would be a fast-forward merge, which should be done on the command line, as it is not available on GitHub's Web UI.

In any case, the tagged commit would still be failing CI. Maybe it's not a big deal, as this failure does not impact the final user. Thus I am approving this PR.

Maybe we should think about a recommended procedure for future version bumps. I would vote for PR + fast-forward-merge, and only tag after merging. @hartwork: what would you recommend?

For the record, this is what the git history would look like after this PR is merged, depending on the merge strategy:

    === Squash merge ===

    * xxxxxxx (master) Merge pull request #180 from tenox7/bump
    | * a415384 (tag: 1.6.5) ver bump
    |/
    * 9bbca81 (tag: 1.6.4) bump to 1.6.4
    ⋮

    === Merge commit ===

    * xxxxxxx (master) Merge pull request #180 from tenox7/bump
    |\
    | * 1cd8be8 update expected
    | * a415384 (tag: 1.6.5) ver bump
    |/
    * 9bbca81 (tag: 1.6.4) bump to 1.6.4
    ⋮

    === Fast forward ===

    * 1cd8be8 (master) update expected
    * a415384 (tag: 1.6.5) ver bump
    * 9bbca81 (tag: 1.6.4) bump to 1.6.4
    ⋮

**Comment by hartwork** [comment]
@edgar-bonet ideally the tag would sit on some commit that (1) includes all changes from that release (which tag 1.6.5 violates btw) and (2) is a predecessor to (or equal of) the default branch. Tag latest master after merge satisfies that when targetting the right commit.

**Pull request merged**
