### PR TITLE
Add install and uninstall targets

### PR DESCRIPTION
**Pull request by sjmulder**
PREFIX is where the program is found after installation, e.g. /usr or /usr/local.

DESTDIR can be used by package build tools and such as a staging directory from which the package is created.

### CODE REVIEW

**Comment by tenox7** [comment]
Thank you. Could you also add targets to build rpm and deb if it's not too much to ask?

**Comment by sjmulder** [comment]
I'm afraid that's not as straightforward - in any case I'm not up to the task. You might want to check out [packagecore](https://github.com/BytePackager/packagecore) but ideally the distributions will pick it up and package it.

In fact this PR is prep for packaging in [pkgsrc](http://www.pkgsrc.org/), a cross platform package manager.

**Comment by tenox7** [comment]
Can you update it so there is no conflict with the new Makefile format. My bad I probably should merged this first.

**Comment by sjmulder** [comment]
The PRs conflicted when I made them; a trade off for not wanting one to depend on the other.

I've now also added the man page to the install target.

**Comment by sjmulder** [comment]
Any issues left?

**Comment by tenox7** [comment]
none, thanks!

**Pull request merged**
