### PR TITLE
Extract function `wait_for_events` (follow-up to #98 and #115)

### PR DESCRIPTION
**Pull request by hartwork**
Follow-up to #98 and #115

@edgar-bonet this is just an idea. I'm happy to rebase this onto #148 after its merge. Also, it doesn't block anything about your idea of extracting function `time_till_next_full_second` a la https://github.com/tenox7/ttyplot/pull/146#pullrequestreview-1762721004 before or after. Just an idea :beers:

### CODE REVIEW

**Review by edgar-bonet — COMMENTED** [review]
Well, why not. Could you please rebase on top of current `devel`. I wonder how it will come out. `EVENT_TIMEOUT` will probably have to be renamed (it's more like a “displayed clock is out of date” event) and given a non-zero value that could be or'ed with others. Also, this function may have to inherit the responsibility of updating the global `now`.

Regarding `time_till_next_full_second`, it could well be merged into `wait_for_events`.

**Review by edgar-bonet — APPROVED** [review]
It feels weird that `EVENT_TIMEOUT` is set but never used. But then, from the point of view of separation of concerns, it makes sense that `wait_for_events` doesn't care whether the reported events are ever used.

LGTM!

**Comment by hartwork** [comment]
> It feels weird that `EVENT_TIMEOUT` is set but never used. But then, from the point of view of separation of concerns, it makes sense that `wait_for_events` doesn't care whether the reported events are ever used.

@edgar-bonet I feel the exact same way.


> LGTM!

Cool! Merging…

Is there anything left before a handover from us to Antoni?

**Comment by edgar-bonet** [comment]
I was thinking of supporting negative values. However, I just got a flu, and my available energy is pretty low now. I think it is more reasonable to let that for another round. Let's get all this into Antoni's hands!

PS: Negative values are already somewhat supported, one just has to explicitly ask for them. For instance, `seq -10 0.2 10 | ttyplot -M -10` works just fine.

**Comment by hartwork** [comment]
> I was thinking of supporting negative values. However, I just got a flu, and my available energy is pretty low now. I think it is more reasonable to let that for another round. Let's get all this into Antoni's hands!

@edgar-bonet my best wishes for a smooth recovery! Sounds fair, I'll reply to the related mail saying we'd like to hand over, you'll be in CC. It has less of a chance to go under in GitHub notification noise then, probably.

> PS: Negative values are already somewhat supported, one just has to explicitly ask for them. For instance, `seq -10 0.2 10 | ttyplot -M -10` works just fine.

Good to know!

**Pull request merged**
