### PR TITLE
Updating README.md.

### PR DESCRIPTION
**Pull request by MIvanchev**

### CODE REVIEW

**Review by edgar-bonet — APPROVED** [review]
:+1: Maybe the man page `ttyplot.1` could be updated in the same PR?

**Review by hartwork — APPROVED** [review]
> 👍 Maybe the man page `ttyplot.1` could be updated in the same PR?

@edgar-bonet with branch name `update-readme-file` I'd personally rather vote for a follow-up pull request, or at least consider it fine to be two pull request instead of one.

**Comment by MIvanchev** [comment]
I can do the man page too no problem :+1:

**Review by tenox7 — APPROVED** [review]
LGTM

**Comment by tenox7** [comment]
Thank you very much!

**Pull request merged**
