### PR TITLE
Add support for negative values

### PR DESCRIPTION
**Pull request by gsmecher**
Adds support for negative values. Should clear up #53 and #22.

This is a quick and possibly rough implementation - comments welcome.

### CODE REVIEW

**Review by hartwork — COMMENTED** [review]
@gsmecher I haven't looked at this in detail yet but I should share that @tenox7 and @edgar-bonet and I are in the process of finishing release 1.6.0 based off branch `development` not `master`, ticket #134 has a few details more, we're not far from the finish line (..). It is probably best to get 1.6.0 finished and `development` merged into `master` first and then we can see together how to transplant this new support for negative numbers, some of it may already by there from #115 but I haven't had a closer look yet what's in here. Happy to do that after 1.6.0.

**Comment by gsmecher** [comment]
> @gsmecher I haven't looked at this in detail yet but I should share that @tenox7 and @edgar-bonet and I are in the process of finishing release 1.6.0 based off branch `development` not `master`, ticket #134 has a few details more, we're not far from the finish line (..). It is probably best to get 1.6.0 finished and `development` merged into `master` first and then we can see together how to transplant this new support for negative numbers, some of it may already by there from #115 but I haven't had a closer look yet what's in here. Happy to do that after 1.6.0.

Not a problem - this was a quick first run through negative-value support. If you get there first, great - otherwise I'll look at merging or rewriting post-1.6.0.

**Comment by hartwork** [comment]
@gsmecher with #155 merged, `master` would now be ready for a re-evaluation of support for negative values.

**Comment by tenox7** [comment]
It says there are conflicts in Makefile and ttyplot.c

**Comment by hartwork** [comment]
> @gsmecher with #155 merged, `master` would now be ready for a re-evaluation of support for negative values.

@gsmecher we haven't heard from you for 3+ weeks now. Are you still interested in this pull request?

**Comment by gsmecher** [comment]
I am! My apologies - I'm swamped. I'll find some time soon.

**Comment by gsmecher** [comment]
Closed in favour of #169.

**Pull request closed without merging**
