### PR TITLE
Be robust towards input containing null bytes (regression from #98)

### PR DESCRIPTION
**Pull request by hartwork**
Regression from #98, may need coordination with #115.

### CODE REVIEW

**Comment by edgar-bonet** [comment]
> may need coordination with #115

It indeed does. Your fix seems perfect to me. Should I add this to refactor-input? Or maybe let you rebase this PR once #115 gets merged?

**Comment by hartwork** [comment]
> It indeed does. Your fix seems perfect to me. Should I add this to refactor-input? Or maybe let you rebase this PR once #115 gets merged?

@edgar-bonet I can rebase it onto #115 after merge but if acceptible I would prefer the other way around: merging #131 here first and rebasing #115 onto this after. It would reduce the number of things in flight, get the fix out earlier, and I'm imagining the conflict resolution to be easy here, if not I'd definitely volunteer to do the resolution. It would help us separate bugfixes from the refactoring, which I consider a good thing if feasible.

**Comment by edgar-bonet** [comment]
> It would reduce the number of things in flight

That's exactly why I would like to merge #115 first. It has been “in flight” for quite a while now. But if you insist in getting this first, OK, go ahead.

**Comment by hartwork** [comment]
@edgar-bonet you gave #129 to me where order was more important to me, I don't insist, let's do your #115 before my #131 here then, happy to rebase after, it's still a good deal for me :+1:

**Comment by hartwork** [comment]
@edgar-bonet rebased and ready for review now

**Review by edgar-bonet — APPROVED** [review]
> The last part is a question of view, the former is a question of performance, at least in part. What do you think?

OK, it does make sense.

**Pull request merged**
