### PR TITLE
Adding -v and -h parameters for version and usage.

### LINKED ISSUE #88: Release a new version and support -v option?
I just noticed 1.4 is from 2019 and a lot of features have been implemented since then. Maybe release 1.5 soon? :) Would be also cool if there was a -v option to print out the version and exit immediately. I could provide a MR for this.

### PR DESCRIPTION
**Pull request by MIvanchev**
Closes #88

### CODE REVIEW

**Review by tenox7 — APPROVED** [review]
LGTM

**Comment by tenox7** [comment]
thank you BTW, could you also update the readme / flags section?

**Comment by MIvanchev** [comment]
Sure, right away :+1:

**Comment by MIvanchev** [comment]
Hey, just giving you a heads up that v1.5 is not the one with my changes according to the tag (it's from April for an older commit). I guess v1.5.1 needs to follow soon with the most recent 6 commits :)

**Comment by tenox7** [comment]
oh thank you for noticing this, let me fix it

**Comment by tenox7** [comment]
I think this broke processing arguments/flags. None work for me any more. Please fix?

**Comment by MIvanchev** [comment]
Sec, let me check! Can you tell me what revision you're working with?

**Comment by hartwork** [comment]
> I think this broke processing arguments/flags.

@tenox7 could you do a `git bisect` about it?

**Pull request merged**
